from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('doctor_signup_load/', doctor_signup_load, name="doctor_signup_load"),
    path('doc_signup_post/', doc_signup_post, name="doc_signup_post"),
    path('login_page_load/', login_page_load, name="login_page_load"),
    path('login_data_post/', login_data_post, name="login_data_post"),
    path('doctor_home_load/', doctor_home_load, name="doctor_home_load"),
    path('doc_profile/', doc_profile, name="doc_profile"),
    path('doc_edit_profile_load/', doc_edit_profile_load, name="doc_edit_profile_load"),
    path('doc_edit_profile_post/', doc_edit_profile_post, name="doc_edit_profile_post"),
    path('usr_signup_load/', usr_signup_load, name="usr_signup_load"),
    path('usr_signup_post/', usr_signup_post, name="usr_signup_post"),
    path('usr_home_load/', usr_home_load, name="usr_home_load"),
    path('usr_profile/', usr_profile, name="usr_profile"),
    path('edit_user_profile_load/', edit_user_profile_load, name="edit_user_profile_load"),
    path('edit_user_profile_post/', edit_user_profile_post, name="edit_user_profile_post"),
    path('doctors_list_usr/', doctors_list_usr, name="doctors_list_usr"),
    path('add_patients_load/<id>/', add_patients_load, name="add_patients_load"),
    path('view_doctor_schedule/', view_doctor_schedule, name="view_doctor_schedule"),
    path('add_schedule/<id>/', add_schedule, name="add_schedule"),
    path('add_schedule_post/', add_schedule_post, name="add_schedule_post"),
    path('user_view_slot/<id>', user_view_slot, name="user_view_slot"),
    path('notification/', notification, name="notification"),
    path('notification_dr/', notification_dr, name="notification_dr"),
    path('view_time_slot/<int:id>/', view_time_slot, name='view_time_slot'),
    path('feedback/<int:id>/', feedback, name='feedback'),
    path("feedback_post/", feedback_post, name="feedback_post"),
    path("view_feedback/<int:id>/", view_feedback, name="view_feedback"),
    path('book_doctor/', book_doctor, name="book_doctor"),
    path('view_patients/', view_patients, name="view_patients"),
    path('prescripton_page_load/<id>/', prescripton_page_load, name="prescripton_page_load"),
    path('post_prescription/', post_prescription, name="post_prescription"),
    path('view_prescription_doctor/<id>/', view_prescription_doctor, name="view_prescription_doctor"),
    path('view_prescription_user/', view_prescription_user, name="view_prescription_user"),
    path('view_booking_user/', view_booking_user, name="view_booking_user"),
    path('payment/<id>/', paymentt, name="payment"),
    path('payment_post/', payment_post, name="payment_post"),
]
