# Generated by Django 5.1.5 on 2025-02-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_manage_ap', '0002_booking_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
