# Generated by Django 5.1.5 on 2025-02-25 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_manage_ap', '0003_alter_booking_age_alter_booking_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slotperiod',
            name='slot',
        ),
        migrations.AddField(
            model_name='slotperiod',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinic_manage_ap.doc_signup'),
            preserve_default=False,
        ),
    ]
